[
 (patterns)
 (expression/list)
 (expression/apply)
 (expression/infix)
 (data_constructors)
 (record)
 (exports)
 (import_list)
 (declarations)
 (alternatives)
 (patterns)
 (expression/do)
 (expression/conditional)
] @iswap-list
